database_url = "https://placements-3d786-default-rtdb.firebaseio.com"

type = "service_account"
project_id = "placements-3d786"
private_key_id = "66efcb9e48c9a3cbdb962ce7b728200d9ca43900"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDknNU/jRQhY7Hg
OMFQe/KwmixRnSNFD/RzLq8NhGoxcKAJ5x7EM+bUNfEPlLbvZeYrXigTCRxDvl5J
TDGJ2Iy/wKqdLsC5ny0uA/6t0XI49BjsPQC+NbvWGBeONOJcUJs4gElTrh1gYV+X
84JwYSA9sDPuzZ2YUSnU8wjblCdsij+lH1Wu3aRmpZ0Y62lo2gkPJiWSU/IIoOIt
uKgbXwg1TiKp3Y4Mwmo6ZtToyhrVEZ6olGoafJqzo18Ln2EwX6LO2moFIRtXNWSI
bApIPTbCOHOW2pKMBegOrAsxkPu2NZWoRnAhHNNt5ELDBtDE7iO2I3a9oJnsdVvJ
R527krrPAgMBAAECggEABvnra5lZBdA4HREH6SmKVUeAvOujW2SqWRqrS3ZnRsn0
Jq+cWaPOnydkPoCTX1Vuacb7FXwGL+HVZVdpymL6BiuRdhZEQFKlezPlzi6uVYmX
xxtXdFziz5ydmQCivB49L/ZOObtkkkypl5/3mSLsBaXkxJx9FI+JfyhjDhxRYndi
XqndPt4JbjLdt2aEQGrnkPKogWqpEMI6TqSX+U/J/bHgpv499M0uEbjaxyw58xhd
hCsrRptxmBoFjIfc5eGQedD8cRdTvsjFJudMJycKVu3x3A0sBI13hGl3280dykw+
jzb9IwQAlRg9ozEjIxIN4410Wo3UgKA7X3eTw2bFOQKBgQD8AwHBQxo4eJKMswjk
kU5A8+XhqnzPmGIARsqFUM6YdkPE3ZEk+uusI6MaOKxLOZMFNOu8DRTETLdQkN61
UmyO4avTnxS36+DA0Tm4InrrL7k8VCYarziUzDOLKvBp6QeEGxMREQhyxHCh+bK4
y+qNZ3+9XA0L3gfvXfRc4yPUBwKBgQDoOwcTOFUoPFNB4HJdp6OKrqj6/xPwmmYl
nd7SRu9Xd6R7HAqAH2yZdw4toCyQoP8Njet4XXcP58ZBVYCN5z5RIJIy0AmmFapLL
dwiO13vhQQXauahCpairBgcneZfNXG1v7FDomukMNCTFoqKpB1A+GNvG//yDTzhJ
x+SdDRqA+QKBgEBPNB9xVDuc6Sjmdxp8yg9hLgSMURVYuYmAhyXGHTJi26BdOjDJ
p2JiJbkHRVBc/NuTSaTPYcFGInF4xpxW0EUV6ZczPUJB+zS5L5WBlwR1RTvT7XVZ
yYKPKYgWCQu936Eil5b/VbyTzHpJEgZ+Yvh6tOpJlzq0CipXO4iInhf5AoGBAOZL
ux1tTM2k3S/EA8Yqe30I7hxSnpSImOlpB1FKQ7FYACR8zvRbeHWdeH7KJaYgbYQW
kW38l18jFe4Ec8nVd4f/buUIS1p6MG7DcWIuAPSFhee9G0ZUf6pyRN/5rfeCRCis
4iN5k8h9YUX4nXQgA4xBHJoAu4oAIqLQLz8rgnAJAoGBAPON7FqtBBZ1k2ExQOGU
yIkOH1XlbcmbOWCUi5KoDrJp3w0lJjWMmO54jC/k1zjvI3SQHbh1DIK7kYq0imPn
1K/yM3g6QLQnE9kRNxNcRlTjQ5HpyIBh0E4cpRisn+tGpcxrXyVTyfs5khQ6QsQU
faDRze9Qntotl4VEIolacy21
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@placements-3d786.iam.gserviceaccount.com"
client_id = "109951182890829263388"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40placements-3d786.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
