database_url = "https://placements-3d786-default-rtdb.firebaseio.com"

firebase_key = """
{
  "type": "service_account",
  "project_id": "placements-3d786",
  "private_key_id": "cb2fc0405cedae298805865ce592cb1015849f8a",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsEUl0KToUX4rG
K0G1CGYQLi9K2HbZE+qGFgUAlpVzqUTMc2l6Q6VaGpf0KEu905nMF80zzsFP2gd0
7AKA4wI4vpFkor723cCQb4iqCrDAW0+V2gwEzWcoDkZTmp5pWkkIzwGUjzSUUxZT
r1k0PrXiq47T5h92Lp3lWBzWrMuM3AAOsddukGj2zP+ceTiBH7SsokdsRvYFA2fp
ElzMIeyVSIRuKINFHcAjHmCPUjcPIHm4nisky+3u8kFiZ/zOtlT+/5kGpl1NCnFM
w6ZpoCHtpRzncWDHJu07SRW2I1dWI21bxkmyOKt+khzMvpKQwxn/CbADXaHdu/+x
SpSQecPlAgMBAAECggEAPB++Puy48q1/3Eb5KrzIjRbWR5zjym5/IGNJVC9KAaQ/
+gDJ9oL0oEtylUoPTUFHGF2owlWYjsJsoJpnNYodGJ7eRv/nInPR+aY/Zstdf5lo
ccBDOtpbFVAHmucIO1/k7UMIFlUD1mBCCPPYg7z16UJxIfHjRHR9j8n+KbUvWwRi
ANNp+rIGkDCuduWS0Q00OyNHAw09mv2AAtAVAfhopSfEvySYNMlgsU1d6BdI4b3K
FMsHcIVTEMrCOURujqiJ4zpZvG18EQrTo+ObJ1ldA9f9PHnC40bC/LWuXNmJT3cl
85ABCpdwnwu/w9D38YGOjE3MNxQrGLe+iJrcbjx88QKBgQDUpY6pXSfeQ0CvDZA0
h70hBquXLL5ElhjkrkI9ob5bUKmZqnkrf+dYsIXv5Ddb/hMv/ROaB8uR9O2iEI5t
CxbHKBstSpIYmrIS/D3Il33QpTVw3DgL1U27uCAurVjwMQkNLhrdWXY9I7jkxheK
OfKAkpAHK0eDtW/q2KiXUXX4lwKBgQDPJdLiEljr+pxLG4rHiIVw5me09kk7yFBM
ObGsCxJg3iBwQRlIX2BJXlDnMdJFQYoA3HCg/hgQP57nclQs3LgY3VQn3oTykc3f
9gadcPXGsa/T4XhjgrXXo4bcit7+L1aAyneimmW+R5JbZr1CWmAXxVKG8H9EERo7
NXKrADka4wKBgA2wdsWqbJWfaLucOOtYzbEhl8xMohcSPpoCKduD3RhN0g1FbzWA
r2kDPCwcWf//FEcjmK5y0AUeamnjfPfCHf5GM7GvukYBN3OHb4bJUd0rtYwFcUo5
uh5alR/MIwyba4TAshQL3VPER/PaWMuaPWVPihwcCieNd537wqazJNATAoGARadt
StFqjyb86RCA0OlqHXWMR8BNDcokng0EXlp2upXWiIiLTNetU95gC+2ny9vm4LU/
NhNa2hPahe7euRsa2FmME7/yKnK2rGlY/hXevwo+mluFlMh+Bt2Y2o3jv8sBJltu
cQHD1oDQiOV6HFaxWyzhvDggQy4RCPnG7hMsIIsCgYBgVyR+a262NXEGOrwrF2AO
o69newJtcjQekzmbw2cwlAmxi+6HOzNByoYYhBltxM19ogO/PvhqPvd8u83W3sV/
zTs6S3b2/ykbsBz04IHSXpZcSut1vCfQlvIz7BKZhDvkMIbnaGdDjXqP/+NvTz5S
4HJzW7TpdVvvS9LExe0fEA==
-----END PRIVATE KEY-----",
  "client_email": "firebase-adminsdk-fbsvc@placements-3d786.iam.gserviceaccount.com",
  "client_id": "109951182890829263388",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40placements-3d786.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
