database_url = "https://placements-3d786-default-rtdb.firebaseio.com"

type = "service_account"
project_id = "placements-3d786"
private_key_id = "cb2fc0405cedae298805865ce592cb1015849f8a"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsEUl0KToUX4rG
K0G1CGYQLi9K2HbZE+qGFgUAlpVzqUTMc2l6Q6VaGpf0KEu905nMF80zzsFP2gd0
...
...
4HJzW7TpdVvvS9LExe0fEA==
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@placements-3d786.iam.gserviceaccount.com"
client_id = "109951182890829263388"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40placements-3d786.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
