# Use your Web API Key from Firebase Project Settings
api_key = "AIzaSyCzehPjoFVDhizCDS9iZDMPaQSVIL-EAXU" 

# Use your Realtime Database URL
database_url = "https://placements-3d786-default-rtdb.firebaseio.com"
